pylops_mpi/DistributedArray.py
tests/test_distributedarray.py

For #21 
- Added `_check_partition_shape` to check for same partition and local array shape.
- Added `_allreduce` to perform MPI reduction operation.
- Added `ndim` as a parameter.
- Added `_compute_vector_norm` to perform norm using local arrays along axis.
- Added Dot Product.
- Added Norm Method.
- Renamed par tests and add new tests for Dot and norm method to make it more clean.

Add Dot Product and Norm using MPI

---

.github/workflows/build.yml
docs/source/api/index.rst
environment-dev.yml
environment.yml
pylops_mpi/LinearOperator.py
pylops_mpi/__init__.py
pylops_mpi/basicoperators/BlockDiag.py
pylops_mpi/basicoperators/__init__.py
requirements-dev.txt
tests/test_blockdiag.py
tests/test_linearop.py

- Added MPIBlockDiag with _matvec and _rmatvec which now uses `DistributedArray`
- Added MPILinearOperator class 
- Added basic classes(_ScaledLinearOperator, _AdjointLinearOperator, etc) and made them input and output `DistributedArray`.
- Added tests to verify above classes.
- Upgrade scipy to `1.8` and python to `3.8`
- Updated docs for sphinx

Add MPIBlockDiag and MPILinearOperator

---

Makefile

@rohanbabbar04 I noticed that using the servedoc rule I was getting an error. I realized that the path of the doc seems to be different from that of pylops (missing an html folder), so with this small change things work for me.
Please check this is also the case for you and merge if you experience the same :)

Fix servedoc rule

---

docs/source/api/index.rst
pylops_mpi/DistributedArray.py
pylops_mpi/__init__.py
pylops_mpi/optimization/__init__.py
pylops_mpi/optimization/basic.py
pylops_mpi/optimization/cls_basic.py
tests/test_solver.py

- Added `conj()` and `copy()` to `DistributedArray` as they were used quite often.
- Added `CGLS` class similar to pylops but now using `DistributedArray`.
- Added `cgls` method which will be used by users, as we do in pylops(again with `DistributedArray`).
- Added some random tests for both real and complex(test cases are same as pylops).
- Added `cgls` and `CGLS` to docs.
- Also added `cgls` to `__init__.py`(same as pylops).

Added CGLS using DistributedArray

---

tests/test_distributedarray.py

- Some tests were not using `assert_allclose`, better to use `assert_allclose` for `DistributedArray` to check for accurate results. (Since we use it for all our other tests.)

All tests now use assert_allclose

---

Makefile
examples/README.rst
examples/mpi_examples.sh

Like we had discussed..
- Added the `note` to `examples/README.rst`
- Added mpi_examples.sh which runs all the files in the folder, one can run using `sh mpi_examples.sh <num_processes>`
- Also added `run_examples` in the `Makefile`.
- Also changed the `NUM_PROCESSES` in `Makefile` to 3 for quicker results..

Display gallery examples using mpi

---

docs/source/api/index.rst
pylops_mpi/basicoperators/HStack.py
pylops_mpi/basicoperators/__init__.py
tests/test_stack.py

- Added `MPIHStack`
- Added test for MPIHStack.
MPIHStack now works similar to the `pylops.HStack`, I have used the concept -> `HStack(ops) = VStack(ops.H).H`.
```
self.HStack = pylops_mpi.MPIVStack(ops=hops, base_comm=base_comm, dtype=dtype).H
```
which creates the HStack and then called the matvec and rmatvec of MPIVStack.
The docs is pretty much the same as MPIVStack...

Added MPIHStack

---

docs/source/api/index.rst
examples/plot_mpilinop.py
pylops_mpi/LinearOperator.py
tests/test_linearop.py

Adds #47 
- Added support for broadcast in `_matvec` and `_rmatvec`.
- Added a test to check the above..

Added support for broadcast in `_matvec` and `_rmatvec` in MPILinearOperator

---

pylops_mpi/optimization/cls_basic.py
tests/test_solver.py
tutorials/plot_lsm.py

For #46
- Updated CGLS to work with broadcasted arrays
- Added a test to verify the above using MPIHStack
- Added LSM in tutorials section.

Added LSM and Updated CGLS to work with broadcasted arrays

---

tests/test_solver.py

Closes #51 
- Updated tests for MPIBlockDiag and MPIVStack
In the example, you used `BlockDiag(..., forceflat=True)`, but I think `forceflat` has not been released yet, so kept it as BlockDiag.

Updated tests in test_solver

---

docs/source/api/index.rst
pylops_mpi/DistributedArray.py
pylops_mpi/basicoperators/FirstDerivative.py
pylops_mpi/basicoperators/__init__.py
pylops_mpi/utils/decorators.py
tests/test_derivative.py

Taking into consideration #49 
- Added `MPIFirstDerivative`
- Added tests and updated docs..

Added MPIFirstDerivative

---

docs/source/api/index.rst
examples/plot_derivative.py
pylops_mpi/basicoperators/SecondDerivative.py
pylops_mpi/basicoperators/__init__.py
tests/test_derivative.py

- Added `MPISecondDerivative` along axis=0.
- Added tests and updated docs
- Added derivatives examples for `MPIFirstDerivative` and `MPISecondDerivative`.

Added MPISecondDerivative

---

environment-dev.yml
requirements-dev.txt

- [#11604](https://github.com/sphinx-doc/sphinx/issues/11604 ) Sphinx now works with 7.2.2 version
- Sphinx-gallery also updated to 0.14.0

Sphinx-version bug Solved

---

.gitignore
CHANGELOG.md
docs/source/changelog.rst
docs/source/index.rst

- Added Changelog(Prepare for v0.0.1)

Added Changelog

---

docs/source/api/index.rst
examples/plot_derivative.py
pylops_mpi/StackedLinearOperator.py
pylops_mpi/basicoperators/Gradient.py
pylops_mpi/basicoperators/__init__.py
tests/test_derivative.py

closes #62 
- Add docstring to `matvec` and `rmatvec` in StackedLinearOperator.
- Add `MPIGradient`
- Add a test in `test_derivative.py`
- Add an example in `plot_derivative.py`
- Update `index.rst` and added MPIGradient in `basicoperators/__init__.py`

Add MPIGradient

---

examples/plot_cgls.py
pylops_mpi/DistributedArray.py
pylops_mpi/optimization/basic.py
pylops_mpi/optimization/cls_basic.py
tests/test_solver.py
tutorials/lsm.py

Closes #87 and #88 
- Add `base_comm` as a parameter to StackedDistributedArray(Required for cg/cgls, plus it is in all our ops, array)
- Removed code for `x0`, handle printing of steps/solvers.
- Change all the docstrings to support MPIStackedLinearOperator.
- In `lsm` and `plot_cgls`, handle initial guess `x0`.
- Update the tests for existing cg/cgls tests.
- Add new tests for StackedLinearOperators and StackedDistributedArray.

CG/CGLS supporting StackedDistributedArray

---

tests/test_derivative.py
tests/test_distributedarray.py
tests/test_linearop.py
tests/test_solver.py
tests/test_stackedlinearop.py

Closes #101 
- Change `np.float128` to `np.float64` in tests.
- Change `np.complex256` to `np.complex128` in tests.
- Minor change of rtol to 1e-13

Fix datatypes for macos test fails

---

docs/source/gpu.rst
docs/source/index.rst
examples/plot_stacked_array.py
pylops_mpi/DistributedArray.py
pylops_mpi/LinearOperator.py
pylops_mpi/basicoperators/BlockDiag.py
pylops_mpi/basicoperators/FirstDerivative.py
pylops_mpi/basicoperators/SecondDerivative.py
pylops_mpi/basicoperators/VStack.py
pylops_mpi/optimization/cls_basic.py
pylops_mpi/utils/decorators.py

This PR is aimed at extending the capabilities of PyLops-MPI to use of CuPy arrays. This is powered by most of the same routines used in PyLops's CuPy backend.
Following https://github.com/PyLops/pylops-mpi/issues/99, we want to explore the combined use of MPI4py and CuPy to allow creating distributed arrays with locals stored on GPUs and direct communication (without passing from CPU). So far, only minimal changes seem to allow this - see notebooks at https://github.com/PyLops/pylops_notebooks/tree/master/developement-mpi/Cupy_MPI

🚀 Enable use of cupy arrays

---

environment-dev.yml
requirements-dev.txt

Closes #105 
- With the new version of PyLops released, testing for `numpy >=2.0.0`

Test for numpy>=2.0.0

---

tutorials/mdd.py

This PR adds a new tutorial focused on MDD, replicating part of this tutorial https://pylops.readthedocs.io/en/latest/tutorials/mdd.html#sphx-glr-tutorials-mdd-py with distributed functionalities.

doc: added mdd tutorial

---

pylops_mpi/DistributedArray.py

This PR improves the handling of `global_shape` and `local_shapes` in `DistributedArray`, allowing one to pass integers instead of tuples for 1D array:
- For `global_shape` this was already allowed, but a bug has been identified when `local_shapes!=None` since in `_check_local_shapes` this is indexed - see https://github.com/PyLops/pylops-mpi/blob/6d3b1e8fc702378810c6a70cd189dbca4e9f2166/pylops_mpi/DistributedArray.py#L325
- For `local_shapes`, this is a new feature

feat: improved handling of shapes

---

.github/workflows/build.yml
examples/plot_distributed_array.py
pylops_mpi/DistributedArray.py
pylops_mpi/basicoperators/BlockDiag.py
pylops_mpi/waveeqprocessing/MDC.py
tests/test_distributedarray.py
tests/test_fredholm.py
tests/test_linearop.py

See https://github.com/PyLops/pylops-mpi/issues/113

2D-distribution

---

pylops_mpi/optimization/cls_basic.py

This PR adds `sys.stdout.flush()` at the end of every iteration print for the solvers to ensure that  the buffer "flush" - especially useful when running codes on clusters.

feat: flush all prints in solver

---

.github/workflows/build.yml
.github/workflows/deploy-docs.yml
.github/workflows/flake.yml

Update build.yml to support python3.13

---

pylops_mpi/LinearOperator.py
pylops_mpi/StackedLinearOperator.py

This PR improves the docstring of MPILinearOperator and MPIStackedLinearOperators, mostly adding some description of their role within the wider scope of pylops-mpi

doc: improved docstrings of MPILinearOperator and MPIStackedLinearOperator

---

pylops_mpi/DistributedArray.py
pylops_mpi/utils/__init__.py
pylops_mpi/utils/dottest.py
setup.cfg
tests/test_fredholm.py
tutorials/mdd.py

- Replace `MPI.COMM_WORLD` with `self.base_comm`
- Fix `dottest` in `__init__.py`
- Fix flake8 lint

Fix dottest dependency and use base_comm instead of MPI.COMM_WORLD

---

pylops_mpi/DistributedArray.py
pylops_mpi/LinearOperator.py
pylops_mpi/basicoperators/BlockDiag.py
pylops_mpi/basicoperators/FirstDerivative.py
pylops_mpi/basicoperators/HStack.py
pylops_mpi/basicoperators/SecondDerivative.py
pylops_mpi/basicoperators/VStack.py
pylops_mpi/utils/_nccl.py
pylops_mpi/utils/decorators.py
tests_nccl/test_blockdiag_nccl.py
tests_nccl/test_derivative_nccl.py
tests_nccl/test_stack_nccl.py

I added the support for NCCL to the MPIVStack. Along the way, I discover some interesting issue and it may be worth discussing so I initiate this drafted PR
Change Made
DistributedArray.py
- MPIVStack adjoint operation takes decorator `@reshape` which calls `add_ghost_cells()` in this file. `add_ghost_cells()` has to be modified to support NCCL. There two points I want to point out.
1. the call to `self._allgather(cell_fronts)`: this `cell_fronts` are the metadata and is small in size (list of ints, size = total ranks). Under the current implementation, I will dispatch to call NCCL if NCCL is enabled. Should we enforce it to always use MPI instead ?
2. the call to `self.base_comm.send`: this sends the ghost cells to peer and the sent array can be large. Under the current code, it will …

add NCCL support to  add_ghost_cells and operators in /basicoperators

---

docs/source/conf.py
docs/source/installation.rst

- Fixing some Sphinx warnings which can be avoided.

Fix sphinx warnings

---

pylops_mpi/DistributedArray.py

Referring to #144, this fix the bug by using `send/recv` to communicate generic Python objects.
The discussion about the performance implication of `Send/Recv` vs `send/recv` on CuPy array is left to be explored

fix send/recv bug in CuPy + MPI

---

Makefile
tutorials_cupy/lsm_cupy.py
tutorials_cupy/mdd_cupy.py
tutorials_cupy/poststack_cupy.py
tutorials_nccl/poststack_nccl.py

This PR adds a new directory called `tutorials_cupy` which includes tutorials running with CuPy arrays and MPI communicators. 
Following what previously done for `tutorials_nccl`, a couple of new targets are also added to the `Makefile` to allow building the documentation with MPI or MPI/Cupy+MPI or MPI/CuPy+MPI/CuPy+NCCL tutorials.

doc: added tutorials with cupy+mpi

---

docs/source/gpu.rst
pylops_mpi/DistributedArray.py
pylops_mpi/signalprocessing/Fredholm1.py
pylops_mpi/utils/_nccl.py
tests_nccl/test_blockdiag_nccl.py
tests_nccl/test_derivative_nccl.py
tests_nccl/test_distributedarray_nccl.py
tests_nccl/test_fredholm_nccl.py
tests_nccl/test_linearop_nccl.py
tests_nccl/test_ncclutils_nccl.py
tests_nccl/test_solver_nccl.py
tests_nccl/test_stack_nccl.py
tests_nccl/test_stackedarray_nccl.py
tests_nccl/test_stackedlinearop_nccl.py

I introduce the complex number support for NCCL communication here.
Changes made:
- `_nccl.py`  - Previously, the number of elements sent is equivalent to the number of elements in the `send_buf`. To support the complex number, we can simply send 2x of that size (`_nccl_buf_size()`). The receiving data layout does not need changes as it will be according to the `recv_buf`  i.e., it will already  be complex if `send_buf` is complex.
- test files - I enabled all the tests. Some were muted earlier due to lack of complex-number support. Now the NCCL and MPI both have 306 tests.
- `Fredholm1.py` - This likely needs some discussion (please see TODO: comment). Particularly, the private function `_allgather` is called because Ops do not take `base_comm_nccl` as an argument. Also, Fredholm …

Complex-number Support for NCCL & Fredholm NCCL

---

examples/plot_matrixmult.py
tests/test_matrixmult.py

This PR introduces an example and some tests of chaining the new `MPIMatrixMult` operator with a block diagonal operator that applies a first derivative to the different column blocks of the output of the distributed matrix multiplication 
@astroC86, let me know what you think 😄

test/doc: added tests and example of chaining MPIMatrixMult

---

tutorials_nccl/lsm_nccl.py
tutorials_nccl/mdd_nccl.py

This PR is for the documentation of Multi-Dimensional Deconvolution (MDD) and Least-Squares Migration (LSM) under NCCL communication.
It was tested on 3 GPUs and ran successfully.
For quick stats on 3 GPUs (UIUC Delta)
LSM (iterations = 100)
-----------------
CuPy + NCCL     Total time (s) = 1.96
CuPy + MPI.        Total time (s) = 1.94
NumPy + MPI      Total time (s) = 1.19
MDD (iterations = 50)
-----------------
CuPy + NCCL      Total time (s) = 1.62
CuPy + MPI          Total time (s) = 2.57
NumPy + MPI       Total time (s) = 6.83
The LSM result is not yet as expected. It could be that the input size is too small for the GPU computations.
Further tests will be carried out.

tutorials for LSM and MDD using NCCL

---

.github/workflows/build.yml
Makefile
tests/test_distributedarray.py
tests/test_fredholm.py
tests/test_solver.py

This PR fixes a number issues that arose when trying to increase the number of ranks in the test suite to 9 or 16. 
As a consquence, I have also decided to modify the GA `build` to run tests with 2,4,9 ranks instead of 2,3,4

test: fix tests not working with high nranks and change GA to test that

---

pylops_mpi/basicoperators/Laplacian.py

Fixes #149 
- Use `get_normalize_axis_index` from `pylops.utils.backend`

Fix Warning in Laplacian

---

docs/source/api/index.rst
docs/source/benchmarking.rst
docs/source/index.rst
pylops_mpi/utils/__init__.py
pylops_mpi/utils/benchmark.py

Added `benchmarking.rst` page to the documentation and `benchmark` and `mark` to the API page

doc: added benchmark to doc
