PyLops/pylops-mpi

- examples/distributed_array.py
- pylops_mpi/DistributedArray.py
- pylops_mpi/__init__.py
- tests/test_distributedarray.py
For #5 
- Enum for Broadcast and Scatter.
- Updated the tests and example accordingly
- Also added `DistributedArray` to `pylops_mpi/__init__.py`
> Added Partition Enum 

- .github/workflows/flake.yml
- pylops_mpi/DistributedArray.py
- tests/test_distributedarray.py
-  Added `flake8`to workflows.
> Add flake.yml

- .github/workflows/deploy-docs.yml
For #14 
- Added `deploy-docs.yml` to deploy sphinx-docs on github pages
> Deploy Sphinx-docs

- Makefile
- environment-dev.yml
- environment.yml
- requirements-dev.txt
- setup.py
Solves #17 
-  Add `environment.yml`
- Add `environment-dev.yml`
- Use `pylops>=2.0`
- Add `matplotlib` to install_requires
> Add environment.yml

- Makefile
- docs/source/conf.py
Solves #19 
- Added `doc`, `docupdate` and `servedoc` in Makefile
- Made minor changes to remove warnings.
> Makefile update for docs

- README.md
- examples/plot_distributed_array.py
- tests/test_distributedarray.py
For #16 
- Updated the README.md
- As in the [Discussion #1](https://github.com/PyLops/pylops-mpi/discussions/1), Changed the shape to (10, 5) in example, also changed the shape in tests
> Updated Readme

- docs/source/api/index.rst
- docs/source/conf.py
- docs/source/index.rst
- pylops_mpi/DistributedArray.py
> Add sphinx docs for api

- docs/source/api/index.rst
- pylops_mpi/basicoperators/VStack.py
- pylops_mpi/basicoperators/__init__.py
- tests/test_stack.py
Adds #33 
- Added MPIVStack with docs.
- Added Tests
> Added MPIVStack

- pylops_mpi/__init__.py
- tutorials/plot_post_stack_inversion.py
#34 Part-1
- Updated the example to use inversion using CGLS
- Also reduced the model shape(reduces time in building the sphinx docs, this was also implemented in this [example](https://pylops.readthedocs.io/en/stable/tutorials/poststack.html)) 
- Added the plot for inversion...
> Updated Inversion Example using CGLS solver

- examples/plot_cgls.py
Adds example for #39 
- Added CGLS example using MPIBlockDiag
> Added cgls example

- pylops_mpi/DistributedArray.py
- Currently we assume that the person will input equal arrays at each rank
> Inconsistency in broadcast

- examples/plot_stacking.py
- Added `MPIVStack` example(Vertical Stacking).
- Added `MPIHStack` example(Horizontal stacking).
- Added `MPIBlockDiag` example(For Block Diagonal example).
> Added Stacking examples

- pylops_mpi/DistributedArray.py
- Added method `add_ghost_cells` which adds ghost cells to the local arrays either from the previous or next process.
> Added add_ghost_cells to DistributedArray

- environment-dev.yml
- requirements-dev.txt
- Add `numba` to requirements-dev.txt
- Add `numba` to environment-dev.yml
> Added numba to requirements

- docs/source/api/index.rst
- examples/plot_derivative.py
- pylops_mpi/basicoperators/Laplacian.py
- pylops_mpi/basicoperators/__init__.py
- tests/test_derivative.py
For #56 (2)
- Added `MPILaplacian`
- Added tests for laplacian
- Added docs to MPILaplacian
> Added MPILaplacian

- docs/source/adding.rst
- docs/source/contributing.rst
- docs/source/credits.rst
- docs/source/index.rst
- docs/source/installation.rst
Closes #63 
Added Documentation for the following: 
Currently under the `Installation for Users` section, two installation methods have been added: 
```
make install_conda
```
and 
```
make install
```
> Added Documentation

- .github/workflows/deploy-docs.yml
- environment-dev.yml
- requirements-dev.txt
- Currently setting to `v<7.2.0` for it to work
> sphinx v7.2.0 seems buggy

- LICENSE
Closes #70 
- Changed License to LGPL-3.0
> Changed License to LGPL-3.0

- docs/source/api/index.rst
- pylops_mpi/optimization/__init__.py
- pylops_mpi/optimization/basic.py
- pylops_mpi/optimization/cls_basic.py
- tests/test_solver.py
- Added `CG` class
- Added `cg` method
- Added test for cg
- Added docs
> Added CG Solver

- tutorials/plot_post_stack_inversion.py
Closes #34 
- Updated example for regularized inversion to use `MPILaplacian`
> Added MPILaplacian to reg inversion example

- .github/workflows/build.yml
- tests/test_solver.py
- Added `forceflat=True` to fix build
- Minor: Added Build for python 3.11
> Add build for python 3.11

- CHANGELOG.md
- docs/source/changelog.rst
Modified changelog files for the release of v0.0.2
> Prepare for v0.0.2

- .github/workflows/build.yml
Closes #92 
- Add python 3.12 to `build.yml`.
> Add tests for python 3.12

- README.md
- Add `pypi` version to Readme.md
> Update Readme to include pypi version

- docs/source/api/index.rst
- examples/plot_mdc.py
- pylops_mpi/__init__.py
- pylops_mpi/basicoperators/__init__.py
- pylops_mpi/signalprocessing/Fredholm1.py
- pylops_mpi/signalprocessing/__init__.py
- pylops_mpi/waveeqprocessing/MDC.py
- pylops_mpi/waveeqprocessing/__init__.py
- tests/test_fredholm.py
- tests/test_solver.py
This PR introduces 2 new operators, namely `MPIFredholm1` and `MPIMDC`, which allow testing the third and last use-case described in the https://github.com/PyLops/pylops/wiki/GSoC-2023-Project-Ideas (e.g., `Both model and data are available in all nodes (or just in the master)`).
Tests are also provided for `MPIFredholm1` and an example is provided for `MPIMDC`
> feat: added MPIFredholm1 and MPIMDC

- joss/paper.bib
- joss/paper.md
> Made changes to paper.md

- README.md
We just got our paper published 🚀 🥳
- Add Joss link to README
> Add joss paper link
